### ISSUE TITLE
running sGuard on solc >= 0.8.0

### ISSUE THREAD

**Issue by SunBeomSo** [duytai/sGuard#23]
Hi,

I am trying to run sGuard on solc >= 0.8.0.
It seems sGuard runs well on solc < 0.8.0, but it produces the following error message for the contract below.

How can I run sGuard successfully on solc >= 0.8.0 ?

* Error message
```
/home/ssb/sGuard/src/index.js:37
const { attributes: { name } } = children[children.length - 1]
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/home/ssb/sGuard/src/index.js:37:52)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

* Tested contract
```
pragma solidity ^0.8.0;
//pragma solidity^0.4.26;

contract Fund {
  mapping(address => uint) balances;
  uint counter = 0;
  uint dontFixMe = 0;

  function main(uint x) public {
    if (counter < 100) {
      // msg.sender.send(x + 1);
      payable(msg.sender).send(x + 1);
      counter += 1;
      dontFixMe ++;
    }
  }
}
```

**Comment by SunBeomSo** [comment]
When I ran sGuard by providing the name of the main contract, sGuard produced a similar error message:
```
/home/ssb/sGuard/src/index.js:39
const { attributes: { name } } = children.find(({attributes: { name }}) => name == mainName)
                                          ^

TypeError: Cannot read property 'find' of undefined
    at Object.<anonymous> (/home/ssb/sGuard/src/index.js:39:43)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```


 
where I modified the index.js at https://github.com/duytai/sGuard/blob/master/src/index.js#L37 by the following code snippet (following the suggestion in https://github.com/duytai/sGuard/issues/20) and ran the command ``npm run dev Fund``:

```
let mainName = process.argv[2]
const { attributes: { name } } = children.find(({attributes: { name }}) => name == mainName)
```

**Comment by duytai** [comment]
hi @SunBeomSo 
I rely on AST generated by compiler to do instrumentation. However, the structure of AST is different across different compiler versions
